export enum AuthAuditEventType {
  // Mobile — login lifecycle
  MOBILE_LOGIN_SUCCESS       = 'MOBILE_LOGIN_SUCCESS',
  MOBILE_LOGIN_FAILURE       = 'MOBILE_LOGIN_FAILURE',
  MOBILE_REFRESH_SUCCESS     = 'MOBILE_REFRESH_SUCCESS',
  MOBILE_REFRESH_REJECTED    = 'MOBILE_REFRESH_REJECTED',
  MOBILE_LOGOUT              = 'MOBILE_LOGOUT',
  LOGOUT_ALL_SESSIONS        = 'LOGOUT_ALL_SESSIONS',
  DEVICE_REBOUND             = 'DEVICE_REBOUND',

  // Mobile — rejection events
  DEVICE_MISMATCH_REJECTED   = 'DEVICE_MISMATCH_REJECTED',
  STALE_SESSION_REJECTED     = 'STALE_SESSION_REJECTED',
  FORCED_RELOGIN_REQUIRED    = 'FORCED_RELOGIN_REQUIRED',

  // Admin — login lifecycle
  ADMIN_LOGIN_SUCCESS        = 'ADMIN_LOGIN_SUCCESS',
  ADMIN_LOGIN_FAILURE        = 'ADMIN_LOGIN_FAILURE',
  ADMIN_LOGOUT               = 'ADMIN_LOGOUT',
  ADMIN_ACCOUNT_LOCKED       = 'ADMIN_ACCOUNT_LOCKED',

  // Session revocation — admin ACTIONS
  SESSION_VERSION_BUMPED     = 'SESSION_VERSION_BUMPED',
  FORCED_RELOGIN_SET         = 'FORCED_RELOGIN_SET',

  // Account management
  PASSWORD_RESET_REQUESTED   = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED   = 'PASSWORD_RESET_COMPLETED',
  INVITE_SENT                = 'INVITE_SENT',
  INVITE_ACCEPTED            = 'INVITE_ACCEPTED',
  ACCOUNT_DEACTIVATED        = 'ACCOUNT_DEACTIVATED',
  ACCOUNT_REACTIVATED        = 'ACCOUNT_REACTIVATED',
  ADMIN_CREATED              = 'ADMIN_CREATED',
  ADMIN_ROLE_CHANGED         = 'ADMIN_ROLE_CHANGED',

  // Firebase provisioning
  FIREBASE_PROVISION_SUCCESS = 'FIREBASE_PROVISION_SUCCESS',
  FIREBASE_PROVISION_FAILED  = 'FIREBASE_PROVISION_FAILED',
  FIREBASE_PROVISION_RETRY   = 'FIREBASE_PROVISION_RETRY',
}
